#!/bin/sh

if [ "$1" = "" ]; then
  echo "Error: specify your blog content directory’s fullpath" >&2
  exit 1
fi

if [ ! -e .env ]; then
  echo "INFO: file \".env\" not found, create sample"
  cp .env.sample .env
fi

fullpath=$(dirname $(realpath $0))

ln -s $fullpath/bin $1
